FROM centos:latest

WORKDIR /app
RUN yum install -y \
    python-devel \
    python-setuptools \
    gcc-c++ \
    openssl-devel \
    bash
    
RUN easy_install pip
RUN curl https://packages.microsoft.com/config/rhel/7/prod.repo > /etc/yum.repos.d/mssql-release.repo
RUN ACCEPT_EULA=Y yum install -y mscodbcsql
RUN ACCEPT_EULA=Y yum install -y mssql-tools
RUN yum install -y unixODBC-devel

RUN pip install pyodbc
COPY ./app

CMD ["usr/bin/python", "-i", "/app/test.py"]
